"""initial3

Revision ID: 9389be7138dd
Revises: bd03289e2372
Create Date: 2023-06-17 16:35:26.974049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9389be7138dd'
down_revision = 'bd03289e2372'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
